version: "3.8"
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mymicroservicesdb
      SPRING_DATASOURCE_USERNAME: fguyard
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - db
    networks:
      - springnet

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: mymicroservicesdb
      POSTGRES_USER: fguyard
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - springnet

volumes:
  pgdata:

networks:
  springnet:
